### ISSUE TITLE
NPM scope

### ISSUE THREAD

**Issue by wessberg** [rx-ts/rollup-plugin-ts#2]
Hi there,

I'm the author of the original package that your fork is based on: https://github.com/wessberg/rollup-plugin-ts.
I have no problems with you forking the package, I'm glad you can use it. Feel free to do whatever you like (it is MIT licensed). However, I see that you have published it on NPM unscoped (as `rollup-plugin-ts`), and I do think that may lead to confusion as to what's the original package, and what's the fork. I've been considering moving from `@wessberg/rollup-plugin-ts` to `rollup-plugin-ts` or in someway using it as an alias to have both, so I was wondering if you would publish your package under a scope to avoid such confusion?

// Frederik

**Comment by JounQin** [comment]
@wessberg Yep, of course, I've add use as owner of npm package.
I just get the ownership from @localvoid a few days ago, and I'm very glad to dedicate it again to its correct author.
